//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class missatges
    {
        public int id { get; set; }
        public string asumpte { get; set; }
        public string cos { get; set; }
        public int id_usuari { get; set; }
        public int id_grup { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual grups grups { get; set; }
        public virtual usuaris usuaris { get; set; }
    }
}
